-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 17:53:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teams` (
  `id` INT NOT NULL,
  `leader_name` VARCHAR(45) NULL,
  `project_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`qualifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`qualifications` (
  `id` INT NOT NULL,
  `skills` VARCHAR(45) NULL,
  `experience` INT(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidates` (
  `id` INT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `team_id` INT(2) NULL,
  `company_id` INT(4) NULL,
  `qualification_id` INT(1) NULL,
  `teams_id` INT NOT NULL,
  `qualifications_id` INT NOT NULL,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `teams_id`, `qualifications_id`, `companies_id`),
  INDEX `fk_candidates_teams_idx` (`teams_id` ASC),
  INDEX `fk_candidates_qualifications1_idx` (`qualifications_id` ASC),
  INDEX `fk_candidates_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_candidates_teams`
    FOREIGN KEY (`teams_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidates_qualifications1`
    FOREIGN KEY (`qualifications_id`)
    REFERENCES `mydb`.`qualifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidates_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `company_id` INT(4) NULL,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `companies_id`),
  INDEX `fk_departments_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_departments_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
